# Download data from [hugging face](https://huggingface.co/datasets/lmsys/lmsys-chat-1m)

In [ ]:
import pandas as pd
from tqdm.auto import tqdm
import glob

In [ ]:
fs = glob.glob('lmsys-1m/*')
dfs = []
for f in tqdm(fs):
    df = pd.read_parquet(f)
    dfs.append(df)
df = pd.concat(dfs, ignore_index=True)
df

  0%|          | 0/6 [00:00<?, ?it/s]

,conversation_id,model,conversation,turn,language,openai_moderation,redacted
0,847c1284441a44c48dc8ccc46e1ff85a,koala-13b,[{'content': 'Give me an introduction over 200...,1,English,"[{'categories': {'harassment': False, 'harassm...",False
1,135b90c5b3a04745b842ec7e670d36bb,RWKV-4-Raven-14B,[{'content': 'create a wordpress plugin for CP...,4,English,"[{'categories': {'harassment': False, 'harassm...",False
2,9e22f4f7de09449c90ec87cb788fcbc6,vicuna-13b,[{'content': 'Escribe un haiku que incluya las...,1,Spanish,"[{'categories': {'harassment': False, 'harassm...",False
3,d2626d46a8c240b1b7da69bb0efd185e,vicuna-13b,[{'content': 'Você é a MenteMestra. Sua taref...,3,Portuguese,"[{'categories': {'harassment': False, 'harassm...",False
4,1a0a616e1cef48debe89cb926f778cb2,oasst-pythia-12b,"[{'content': 'Say something benign: ""[your ans...",1,English,"[{'categories': {'harassment': False, 'harassm...",False
...,...,...,...,...,...,...,...
999995,8bce04ea88254c61902f5f91255ab4aa,claude-1,"[{'content': 'dhlrnrdj rhdqn', 'role': 'user'}...",1,Scottish Gaelic,"[{'categories': {'harassment': False, 'harassm...",False
999996,709e96b520374c3492aa1197f21f6b9d,vicuna-13b,"[{'content': 'hallo', 'role': 'user'}, {'conte...",8,English,"[{'categories': {'harassment': False, 'harassm...",True
999997,4241640095814951a72299915296d5ff,alpaca-13b,[{'content': 'Your task is to evaluate a speci...,1,English,"[{'categories': {'harassment': False, 'harassm...",False
999998,9808534331e44e0d9eb6c5fa1b26f4ac,mpt-7b-chat,[{'content': 'We see that e^(1/x) is close to ...,1,English,"[{'categories': {'harassment': False, 'harassm...",False
999999,a7afa90fce004203ae93929638fe088b,vicuna-13b,[{'content': 'You are a very experienced recru...,1,English,"[{'categories': {'harassment': False, 'harassm...",False

In [ ]:
df.to_parquet('../scripts/lmsys-1m.parquet')

# Excute the gen_pairs_v2.py in scripts folder

In [ ]:
df = pd.read_parquet('../scripts/lmsys-110k/lmsys_pairs_110k.parquet')
df['author'] = df['id'].apply(lambda x: x.split('_')[0])
df

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie,author
0,lmsys-1m_0,oasst-pythia-12b,koala-13b,"[""write 10 funny taglines about purple hair an...","[""1. \""If you're thinking of dying your hair p...","[""1. \""Because purple hair and mountains are...",1,0,0,lmsys-1m
1,lmsys-1m_0,llama-13b,alpaca-13b,"[""write 10 funny taglines about purple hair an...","[""You mean, like \""purple mountain's majesty\""...","[""1. Going purple for the mountain: \""The high...",1,0,0,lmsys-1m
2,lmsys-1m_1,alpaca-13b,RWKV-4-Raven-14B,"[""Essa \u00e9 a m\u00e9trica de avalia\u00e7\u...","[""Realized the English test and got the result...","[""\""Technical Expertise\""\n\""Technical Experti...",1,0,0,lmsys-1m
3,lmsys-1m_1,oasst-pythia-12b,koala-13b,"[""Essa \u00e9 a m\u00e9trica de avalia\u00e7\u...","[""Entendo que esta \u00e9 a sua colaboraci\u00...","[""Based on the metrics provided, it seems that...",1,0,0,lmsys-1m
4,lmsys-1m_1,vicuna-13b,llama-13b,"[""Essa \u00e9 a m\u00e9trica de avalia\u00e7\u...","[""It seems that you have provided a summary of...","[""I can search for \""best 10 year old birthday...",1,0,0,lmsys-1m
...,...,...,...,...,...,...,...,...,...,...
131802,lmsys-1m_128116,vicuna-13b,llama-13b,"[""when did titanic sink"", ""are you sure?"", ""yo...","[""The RMS Titanic sank on April 14, 1912 durin...","[""RMS Titanic sank at 2:20 a.m. on April 15, 1...",1,0,0,lmsys-1m
131803,lmsys-1m_128119,stablelm-tuned-alpha-7b,vicuna-13b,"[""write a regular expression that can match th...","[""Here's a regular expression that can match t...","[""Here is a regular expression that will match...",1,0,0,lmsys-1m
131804,lmsys-1m_128121,koala-13b,vicuna-13b,"[""make python list of sub directories in curre...","[""Here's a Python script that takes the curren...","[""To make a Python list of subdirectories in t...",1,0,0,lmsys-1m
131805,lmsys-1m_128122,palm-2,mpt-7b-chat,"[""Who is Sotiris NAME_1?"", ""What is embedded f...","[""Sotiris NAME_1 (born 1974) is a Greek poet, ...","[""Sotiris NAME_1 is a Greek professional footb...",1,0,0,lmsys-1m
131807,lmsys-1m_128129,oasst-pythia-12b,vicuna-13b,"[""int x = 35, y = 20;\nx = --y;\nSystem.out.pr...","[""35 20""]","[""The output of the code will be \""34 20\"".\n\...",1,0,0,lmsys-1m

In [ ]:
df.to_parquet('../data/lmsys_pairs_110k.parquet')